services:
  arrr-dash:
    build: .
    container_name: arrr-dash
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
